# Generated by Django 5.0 on 2023-12-05 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalityTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=20)),
                ('question2', models.CharField(max_length=20)),
                ('question3', models.CharField(max_length=20)),
            ],
        ),
    ]
