# Generated by Django 5.0 on 2023-12-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalitytestresult',
            name='question1',
        ),
        migrations.RemoveField(
            model_name='personalitytestresult',
            name='question2',
        ),
        migrations.RemoveField(
            model_name='personalitytestresult',
            name='question3',
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='question1_response',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='question2_response',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='question3_response',
            field=models.IntegerField(default=3),
        ),
    ]
