# Generated by Django 5.0 on 2023-12-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0002_remove_personalitytestresult_question1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytestresult',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='agreeable_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='case_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='conscientiousness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='extraversion_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='neuroticism_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='openness_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='sex',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question1_response',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question2_response',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question3_response',
            field=models.CharField(max_length=255),
        ),
    ]
