# Generated by Django 5.0 on 2023-12-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_personalitytestresult_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=255)),
                ('average_agreeable_score', models.FloatField(default=0.0)),
                ('average_extraversion_score', models.FloatField(default=0.0)),
                ('average_openness_score', models.FloatField(default=0.0)),
                ('average_conscientiousness_score', models.FloatField(default=0.0)),
                ('average_neuroticism_score', models.FloatField(default=0.0)),
            ],
        ),
    ]
