# Generated by Django 5.0 on 2023-12-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0004_countryprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question1_response',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question2_response',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question3_response',
            field=models.IntegerField(),
        ),
    ]
