# Generated by Django 5.0 on 2023-12-13 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0005_alter_personalitytestresult_question1_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question1_response',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question2_response',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question3_response',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
