# Generated by Django 5.0 on 2023-12-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0006_alter_personalitytestresult_question1_response_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question1_response',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=0),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question2_response',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=0),
        ),
        migrations.AlterField(
            model_name='personalitytestresult',
            name='question3_response',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=0),
        ),
    ]
