# Generated by Django 5.0 on 2023-12-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0007_alter_personalitytestresult_question1_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalitytestresult',
            name='question4_response',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=0),
        ),
        migrations.AddField(
            model_name='personalitytestresult',
            name='question5_response',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=0),
        ),
    ]

